apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: z7wuwwo6n-go-gitops
  description: This is GitOps manifest for z7wuwwo6n-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: z7wuwwo6n-go
    janus-idp.io/tekton: z7wuwwo6n-go
    backstage.io/kubernetes-id: z7wuwwo6n-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:z7wuwwo6n-go
